### Test server
GET http://localhost:3000/

### Test server Array
GET http://localhost:3000/contacts

### Test server objectId 1
GET http://localhost:3000/contacts/6962d83551bd27558b58ca8e

### Test server objectId 2
GET http://localhost:3000/contacts/6962d92251bd27558b58ca8f

### Test server objectId 3
GET http://localhost:3000/contacts/6962d95051bd27558b58ca90

### Test server CREATE
POST http://localhost:3000/contacts
Content-Type: application/json

{
    "firstName": "Mario",
    "lastName": "Ramirez",
    "email": "Mario.Ramirez@test.com",
    "favoriteColor": "Green",
    "birthday": "11/11/1999"
  }


### Test server UPDATE
PUT http://localhost:3000/contacts/696dbb183561bb3b284dbc53
Content-Type: application/json

{
    "firstName": "Nuvia",
    "lastName": "Keith",
    "email": "Nuvia.Keith@test.com",
    "favoriteColor": "Red",
    "birthday": "12/12/1985"
  }

### Test server DELETE
DELETE http://localhost:3000/contacts/696dbb183561bb3b284dbc53