### Test server
GET http://localhost:5500/

### Test server Array
GET http://localhost:5500/jobs

### Test server objectId 1
GET http://localhost:5500/jobs/697986cfa5b71fd876547945

### Test server CREATE
POST http://localhost:5500/jobs
Content-Type: application/json

{
    "jobNumber": 62168,
    "client": "hello",
    "office": "hello",
    "projectName": "hello",
    "lab": "hello",
    "receivedDate": "2025-12-26",
    "dueDate": "2026-02-11",
    "status": false
  }


### Test server UPDATE
PUT http://localhost:5500/jobs/69798677a5b71fd876547944
Content-Type: application/json

{
    "jobNumber": 62017,
    "client": "Geosyntec",
    "office": "Ohio",
    "projectName": "BKK Landfill",
    "lab": "Eurofins",
    "receivedDate": "2026-01-26",
    "dueDate": "2026-02-18",
    "status": true
  }

### Test server DELETE
DELETE http://localhost:5500/jobs/69798677a5b71fd876547944